# Generated by Django 4.2.1 on 2023-06-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals/images'),
        ),
    ]
