# Generated by Django 4.2.1 on 2023-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_info', '0002_animal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='animal_images'),
        ),
    ]
