# Generated by Django 4.2.1 on 2023-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rental_created_at_rental_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
