# Generated by Django 4.2.1 on 2023-06-02 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_vehicle_return_date_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
