# Generated by Django 4.2.1 on 2023-06-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_category_country_director_remove_film_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.AddField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_created', to='film.country'),
        ),
    ]
