# Generated by Django 4.2.1 on 2023-06-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_remove_film_country_film_created_in_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films_created', to='film.country'),
        ),
    ]
