# Generated by Django 4.2.1 on 2023-06-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_remove_film_director_film_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(to='film.director'),
        ),
    ]
